[projects]

  [projects.default]
  contents = [
    "about",
    "what-is-sciml",
    "optimizing-serial-code",
    "appendix",
    "references",
  ]

  # Full URL, required for the sitemap and robots.txt.
  online_url = "https://booktemplate.huijzer.xyz"

  # Extra directories to be copied.
  extra_directories = []

  # Port used by serve()
  port = 8004

  output_filename = "SciML_Book"
